# Site settings
title: Praise Amonye's Professional Portfolio
theme: jekyll-theme-minimal
email: amonyepraise@gmail.com
description: >-
  Enthusiastic advocate for the intersection of mathematics, artificial intelligence, and scientific advancement. Committed to leveraging cutting-edge technologies to drive innovation and discovery.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrpraise.github.io" # replace 'yourgithubusername' with your actual GitHub username
github_username: MrPraise # replace 'yourgithubusername' with your actual GitHub username

# Build settings
markdown: kramdown
theme: minima

# Exclude these files and directories from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Customization options
minima:
  skin: classic

# Enable pagination
paginate: 5
paginate_path: "/page:num/"

# Author details
author:
  name: Praise Amonye
  email: amonyepraise@gmail.com
  nationality: Nigerian
  address: Number 328, Minonkpo, Gbejromede, Cotonou, Benin Republic

# Education
education:
  - degree: Masters in Financial Engineering
    institution: WorldQuant University
    location: New Orleans, United States
    dates: 07/06/2023 – CURRENT
    website: https://www.wqu.edu
  - degree: Kaggle Certification
    institution: Kaggle
    location: California, United States
    dates: 16/10/2023 – 19/01/2024
    website: https://www.kaggle.com
  - degree: Data Science Certification
    institution: WorldQuant University
    location: New Orleans, United States
    dates: 15/06/2023 – 02/12/2023
    website: https://www.wqu.edu
  - degree: Bachelor of Science in Mathematics
    institution: University of Ilorin
    location: Ilorin, Nigeria
    dates: 14/12/2015 – 09/09/2019
    website: https://www.unilorin.edu.ng

# Work Experience
work_experience:
  - position: Co-founder and Chief Data Scientist
    company: OASYS TECH HUB
    location: Cotonou, Benin
    dates: 30/01/2023 – CURRENT

  - position: Class Teacher
    company: SALEM ACADEMY
    location: Lugbe, Abuja, Nigeria
    dates: 14/10/2020 – 09/09/2022
    responsibilities:
    
# Projects
projects:
  - title: Direct and Iterative Methods for Solution of System of Linear Equations
    date: 2019
    description: Measured the efficacy of different methods to solve system of linear equations and provided recommendations on the best approach for different systems.
  - title: Advancing Mosquito Control in West Africa: A Data-Driven Approach Using Machine Learning and AI
    date: 06/02/2023 – CURRENT
    description: Using Machine Learning and AI to control the yearly adverse effect of mosquito parasites in the Sub-Sahel. The findings could be extended to other regions for the control of malaria.
  - title: Impact Drive: Moral Values Education Initiative
    date: 09/09/2022 – 17/12/2023
    description: An initiative dedicated to instilling moral values in primary and secondary school students across Benin Republic through interactive workshops and activities.

# Skills
skills:
  - Programming: C, Java, Apex, Html Python, OCaml, OpenGL
  - Tools: Google Suite (Docs, Sheets, Slides), Microsoft Office (Word, PowerPoint), Photoshop, Adobe
  - Other: Team-work oriented, Good listener and communicator, Social Media, Organizational and planning skills

# Language Skills
languages:
  - Idoma: Mother tongue
  - Hausa: Listening (B1), Reading (A2), Spoken Production (B2), Spoken Interaction (B1), Writing (A2)
  - English: Listening (C2), Reading (C2), Spoken Production (C1), Spoken Interaction (C2), Writing (C2)
  - French: Listening (B1), Reading (B1), Spoken Production (B1), Spoken Interaction (B1), Writing (A2)

# Hobbies and Interests
hobbies:
  - Reading
  - Basketball
  - Singing
